### ISSUE TITLE
Accuracy calculation

### ISSUE THREAD

**Issue by bahaspieler** [juliandewit/kaggle_ndsb2017#52]
in your submission, only the probability of having cancer is calculated. How would you calculate the accuracy of your submission??

**Comment by juliandewit** [comment]
Hello, I did not compute accuracy.
I used logloss on the holdout set(s) with my gradient boosting to assess my models.
Accuracy was very high but this is main due to the data imbalance. (many negative cases).

Final analysis have been done on the real test-set at kaggle.
There was a video of AUC etc on the NVIDIA event.

**Comment by nishat-sayyed** [comment]
Can anyone find the solution to find out the accuracy?

**Comment by juliandewit** [comment]
Accuracy is not a good measure.. 
A better measure is UAC.
For an in-depth analysis see :

[Analysis of 2017 datascience bowl by organiser](http://on-demand.gputechconf.com/gtc/2017/presentation/s7577-bram-van-ginneken-data-science-bowl-lung-chanllenge.pdf)

Note that our solution had the best AUC.
